name: NeXTQuarry
main: net.autumndusk.nextquarry.main.MainClass
version: 1.7.0
description: Adds quarries to vanilla minecraft
author: BeMacized
permissions:
   nextquarry.user.*:
     description: Gives all user permissions for NeXTQuarry.
     default: true
     children:
            nextquarry.user.tier1: true
            nextquarry.user.tier2: true
            nextquarry.user.tier3: true
            nextquarry.user.remove: true
            nextquarry.user.edit: true
   nextquarry.admin:
     description: Gives admin permissions for NeXTQuarry.
     default: op
   nextquarry.user.tier1:
     description: Allows the user to place tier 1 quarries.
   nextquarry.user.tier2:
     description: Allows the user to place tier 2 quarries.
   nextquarry.user.tier3:
     description: Allows the user to place tier 3 quarries.
   nextquarry.user.remove:
     description: Allows the user to remove quarries.
   nextquarry.user.edit:
     description: Allows the user to edit quarries (Upgrades & Fuel).
commands:
   nextquarry:
     description: Gives info on the NextQuarry plugin.
     usage: /nextquarry